version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: interncase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: secret-pw
      DB_PORT: "3306"
      DB_NAME: interncase
      DB_SSL_MODE: disable
volumes:
  db_data:
